namespace ProyectoFinal.ControlUsuario
{
    partial class Registrar_calificacion
    {
        /// <summary> 
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de componentes

        /// <summary> 
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Registrar_calificacion));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.txtPractica1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.GraficaPromedioPractica = new Bunifu.UI.WinForms.BunifuCircleProgress();
            this.pnlIdentificacion = new System.Windows.Forms.Panel();
            this.txtCalificacionFinal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStatus = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMatricula = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPractica2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPractica3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPromedioPracticas = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPromedioExamenes = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtExamenFinal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtParcial2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.GraficaPromedioExamen = new Bunifu.UI.WinForms.BunifuCircleProgress();
            this.txtParcial1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblPractica = new System.Windows.Forms.Label();
            this.lblExamenes = new System.Windows.Forms.Label();
            this.lblPromedioPracticas = new System.Windows.Forms.Label();
            this.lblPromedioExamenes = new System.Windows.Forms.Label();
            this.btnAgregar = new System.Windows.Forms.Button();
            this.pnlIdentificacion.SuspendLayout();
            this.SuspendLayout();
            // 
            // txtPractica1
            // 
            this.txtPractica1.AcceptsReturn = false;
            this.txtPractica1.AcceptsTab = false;
            this.txtPractica1.AnimationSpeed = 200;
            this.txtPractica1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPractica1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPractica1.BackColor = System.Drawing.Color.White;
            this.txtPractica1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPractica1.BackgroundImage")));
            this.txtPractica1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPractica1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPractica1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPractica1.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPractica1.BorderRadius = 1;
            this.txtPractica1.BorderThickness = 1;
            this.txtPractica1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPractica1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPractica1.DefaultText = "";
            this.txtPractica1.FillColor = System.Drawing.Color.White;
            this.txtPractica1.HideSelection = true;
            this.txtPractica1.IconLeft = null;
            this.txtPractica1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica1.IconPadding = 10;
            this.txtPractica1.IconRight = null;
            this.txtPractica1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica1.Lines = new string[0];
            this.txtPractica1.Location = new System.Drawing.Point(21, 343);
            this.txtPractica1.MaxLength = 32767;
            this.txtPractica1.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPractica1.Modified = false;
            this.txtPractica1.Multiline = false;
            this.txtPractica1.Name = "txtPractica1";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPractica1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica1.OnIdleState = stateProperties4;
            this.txtPractica1.Padding = new System.Windows.Forms.Padding(3);
            this.txtPractica1.PasswordChar = '\0';
            this.txtPractica1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPractica1.PlaceholderText = "Práctica 1";
            this.txtPractica1.ReadOnly = false;
            this.txtPractica1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPractica1.SelectedText = "";
            this.txtPractica1.SelectionLength = 0;
            this.txtPractica1.SelectionStart = 0;
            this.txtPractica1.ShortcutsEnabled = true;
            this.txtPractica1.Size = new System.Drawing.Size(136, 37);
            this.txtPractica1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPractica1.TabIndex = 0;
            this.txtPractica1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPractica1.TextMarginBottom = 0;
            this.txtPractica1.TextMarginLeft = 3;
            this.txtPractica1.TextMarginTop = 0;
            this.txtPractica1.TextPlaceholder = "Práctica 1";
            this.txtPractica1.UseSystemPasswordChar = false;
            this.txtPractica1.WordWrap = true;
            // 
            // GraficaPromedioPractica
            // 
            this.GraficaPromedioPractica.Animated = false;
            this.GraficaPromedioPractica.AnimationInterval = 1;
            this.GraficaPromedioPractica.AnimationSpeed = 1;
            this.GraficaPromedioPractica.BackColor = System.Drawing.Color.Transparent;
            this.GraficaPromedioPractica.CircleMargin = 10;
            this.GraficaPromedioPractica.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GraficaPromedioPractica.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.GraficaPromedioPractica.IsPercentage = false;
            this.GraficaPromedioPractica.LineProgressThickness = 10;
            this.GraficaPromedioPractica.LineThickness = 10;
            this.GraficaPromedioPractica.Location = new System.Drawing.Point(220, 526);
            this.GraficaPromedioPractica.Name = "GraficaPromedioPractica";
            this.GraficaPromedioPractica.ProgressAnimationSpeed = 200;
            this.GraficaPromedioPractica.ProgressBackColor = System.Drawing.Color.Gainsboro;
            this.GraficaPromedioPractica.ProgressColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(177)))), ((int)(((byte)(137)))));
            this.GraficaPromedioPractica.ProgressColor2 = System.Drawing.Color.DodgerBlue;
            this.GraficaPromedioPractica.ProgressEndCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.GraficaPromedioPractica.ProgressFillStyle = Bunifu.UI.WinForms.BunifuCircleProgress.FillStyles.Solid;
            this.GraficaPromedioPractica.ProgressStartCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.GraficaPromedioPractica.SecondaryFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GraficaPromedioPractica.Size = new System.Drawing.Size(100, 100);
            this.GraficaPromedioPractica.SubScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.GraficaPromedioPractica.SubScriptMargin = new System.Windows.Forms.Padding(5, -20, 0, 0);
            this.GraficaPromedioPractica.SubScriptText = "";
            this.GraficaPromedioPractica.SuperScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.GraficaPromedioPractica.SuperScriptMargin = new System.Windows.Forms.Padding(5, 20, 0, 0);
            this.GraficaPromedioPractica.SuperScriptText = "%";
            this.GraficaPromedioPractica.TabIndex = 18;
            this.GraficaPromedioPractica.Text = "30";
            this.GraficaPromedioPractica.TextMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.GraficaPromedioPractica.Value = 30;
            this.GraficaPromedioPractica.ValueByTransition = 30;
            this.GraficaPromedioPractica.ValueMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.GraficaPromedioPractica.ProgressChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCircleProgress.ProgressChangedEventArgs>(this.GraficaPromedioPractica_ProgressChanged);
            // 
            // pnlIdentificacion
            // 
            this.pnlIdentificacion.BackColor = System.Drawing.Color.White;
            this.pnlIdentificacion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlIdentificacion.BackgroundImage")));
            this.pnlIdentificacion.Controls.Add(this.txtCalificacionFinal);
            this.pnlIdentificacion.Controls.Add(this.txtStatus);
            this.pnlIdentificacion.Controls.Add(this.txtMatricula);
            this.pnlIdentificacion.Controls.Add(this.txtNombre);
            this.pnlIdentificacion.Location = new System.Drawing.Point(506, 43);
            this.pnlIdentificacion.Name = "pnlIdentificacion";
            this.pnlIdentificacion.Size = new System.Drawing.Size(426, 206);
            this.pnlIdentificacion.TabIndex = 19;
            // 
            // txtCalificacionFinal
            // 
            this.txtCalificacionFinal.AcceptsReturn = false;
            this.txtCalificacionFinal.AcceptsTab = false;
            this.txtCalificacionFinal.AnimationSpeed = 200;
            this.txtCalificacionFinal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCalificacionFinal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCalificacionFinal.BackColor = System.Drawing.Color.Transparent;
            this.txtCalificacionFinal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCalificacionFinal.BackgroundImage")));
            this.txtCalificacionFinal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCalificacionFinal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCalificacionFinal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCalificacionFinal.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCalificacionFinal.BorderRadius = 30;
            this.txtCalificacionFinal.BorderThickness = 0;
            this.txtCalificacionFinal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCalificacionFinal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCalificacionFinal.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCalificacionFinal.DefaultText = "";
            this.txtCalificacionFinal.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            this.txtCalificacionFinal.HideSelection = true;
            this.txtCalificacionFinal.IconLeft = null;
            this.txtCalificacionFinal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCalificacionFinal.IconPadding = 10;
            this.txtCalificacionFinal.IconRight = null;
            this.txtCalificacionFinal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCalificacionFinal.Lines = new string[0];
            this.txtCalificacionFinal.Location = new System.Drawing.Point(179, 116);
            this.txtCalificacionFinal.MaxLength = 32767;
            this.txtCalificacionFinal.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCalificacionFinal.Modified = false;
            this.txtCalificacionFinal.Multiline = false;
            this.txtCalificacionFinal.Name = "txtCalificacionFinal";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCalificacionFinal.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCalificacionFinal.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCalificacionFinal.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCalificacionFinal.OnIdleState = stateProperties8;
            this.txtCalificacionFinal.Padding = new System.Windows.Forms.Padding(3);
            this.txtCalificacionFinal.PasswordChar = '\0';
            this.txtCalificacionFinal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCalificacionFinal.PlaceholderText = "Calificacion Final";
            this.txtCalificacionFinal.ReadOnly = true;
            this.txtCalificacionFinal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCalificacionFinal.SelectedText = "";
            this.txtCalificacionFinal.SelectionLength = 0;
            this.txtCalificacionFinal.SelectionStart = 0;
            this.txtCalificacionFinal.ShortcutsEnabled = true;
            this.txtCalificacionFinal.Size = new System.Drawing.Size(220, 33);
            this.txtCalificacionFinal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCalificacionFinal.TabIndex = 3;
            this.txtCalificacionFinal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCalificacionFinal.TextMarginBottom = 0;
            this.txtCalificacionFinal.TextMarginLeft = 3;
            this.txtCalificacionFinal.TextMarginTop = 0;
            this.txtCalificacionFinal.TextPlaceholder = "Calificacion Final";
            this.txtCalificacionFinal.UseSystemPasswordChar = false;
            this.txtCalificacionFinal.WordWrap = true;
            // 
            // txtStatus
            // 
            this.txtStatus.AcceptsReturn = false;
            this.txtStatus.AcceptsTab = false;
            this.txtStatus.AnimationSpeed = 200;
            this.txtStatus.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStatus.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStatus.BackColor = System.Drawing.Color.Transparent;
            this.txtStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStatus.BackgroundImage")));
            this.txtStatus.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStatus.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStatus.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStatus.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStatus.BorderRadius = 30;
            this.txtStatus.BorderThickness = 0;
            this.txtStatus.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStatus.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStatus.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStatus.DefaultText = "";
            this.txtStatus.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            this.txtStatus.HideSelection = true;
            this.txtStatus.IconLeft = null;
            this.txtStatus.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStatus.IconPadding = 10;
            this.txtStatus.IconRight = null;
            this.txtStatus.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStatus.Lines = new string[0];
            this.txtStatus.Location = new System.Drawing.Point(179, 159);
            this.txtStatus.MaxLength = 32767;
            this.txtStatus.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStatus.Modified = false;
            this.txtStatus.Multiline = false;
            this.txtStatus.Name = "txtStatus";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStatus.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStatus.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStatus.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStatus.OnIdleState = stateProperties12;
            this.txtStatus.Padding = new System.Windows.Forms.Padding(3);
            this.txtStatus.PasswordChar = '\0';
            this.txtStatus.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStatus.PlaceholderText = "Status";
            this.txtStatus.ReadOnly = true;
            this.txtStatus.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStatus.SelectedText = "";
            this.txtStatus.SelectionLength = 0;
            this.txtStatus.SelectionStart = 0;
            this.txtStatus.ShortcutsEnabled = true;
            this.txtStatus.Size = new System.Drawing.Size(220, 34);
            this.txtStatus.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStatus.TabIndex = 2;
            this.txtStatus.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStatus.TextMarginBottom = 0;
            this.txtStatus.TextMarginLeft = 3;
            this.txtStatus.TextMarginTop = 0;
            this.txtStatus.TextPlaceholder = "Status";
            this.txtStatus.UseSystemPasswordChar = false;
            this.txtStatus.WordWrap = true;
            this.txtStatus.TextChanged += new System.EventHandler(this.txtStatus_TextChanged);
            // 
            // txtMatricula
            // 
            this.txtMatricula.AcceptsReturn = false;
            this.txtMatricula.AcceptsTab = false;
            this.txtMatricula.AnimationSpeed = 200;
            this.txtMatricula.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMatricula.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMatricula.BackColor = System.Drawing.Color.Transparent;
            this.txtMatricula.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMatricula.BackgroundImage")));
            this.txtMatricula.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMatricula.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMatricula.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMatricula.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMatricula.BorderRadius = 30;
            this.txtMatricula.BorderThickness = 0;
            this.txtMatricula.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMatricula.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatricula.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMatricula.DefaultText = "";
            this.txtMatricula.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            this.txtMatricula.HideSelection = true;
            this.txtMatricula.IconLeft = null;
            this.txtMatricula.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatricula.IconPadding = 10;
            this.txtMatricula.IconRight = null;
            this.txtMatricula.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatricula.Lines = new string[0];
            this.txtMatricula.Location = new System.Drawing.Point(178, 69);
            this.txtMatricula.MaxLength = 32767;
            this.txtMatricula.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMatricula.Modified = false;
            this.txtMatricula.Multiline = false;
            this.txtMatricula.Name = "txtMatricula";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatricula.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMatricula.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatricula.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatricula.OnIdleState = stateProperties16;
            this.txtMatricula.Padding = new System.Windows.Forms.Padding(3);
            this.txtMatricula.PasswordChar = '\0';
            this.txtMatricula.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMatricula.PlaceholderText = "Matrícula";
            this.txtMatricula.ReadOnly = false;
            this.txtMatricula.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMatricula.SelectedText = "";
            this.txtMatricula.SelectionLength = 0;
            this.txtMatricula.SelectionStart = 0;
            this.txtMatricula.ShortcutsEnabled = true;
            this.txtMatricula.Size = new System.Drawing.Size(220, 33);
            this.txtMatricula.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMatricula.TabIndex = 1;
            this.txtMatricula.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMatricula.TextMarginBottom = 0;
            this.txtMatricula.TextMarginLeft = 3;
            this.txtMatricula.TextMarginTop = 0;
            this.txtMatricula.TextPlaceholder = "Matrícula";
            this.txtMatricula.UseSystemPasswordChar = false;
            this.txtMatricula.WordWrap = true;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = false;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombre.BorderRadius = 30;
            this.txtNombre.BorderThickness = 0;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(179, 23);
            this.txtNombre.MaxLength = 32767;
            this.txtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(233)))));
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties20;
            this.txtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombre.PlaceholderText = "Nombre Completo";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = true;
            this.txtNombre.Size = new System.Drawing.Size(220, 37);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombre.TabIndex = 0;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 3;
            this.txtNombre.TextMarginTop = 0;
            this.txtNombre.TextPlaceholder = "Nombre Completo";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // txtPractica2
            // 
            this.txtPractica2.AcceptsReturn = false;
            this.txtPractica2.AcceptsTab = false;
            this.txtPractica2.AnimationSpeed = 200;
            this.txtPractica2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPractica2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPractica2.BackColor = System.Drawing.Color.White;
            this.txtPractica2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPractica2.BackgroundImage")));
            this.txtPractica2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPractica2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPractica2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPractica2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPractica2.BorderRadius = 1;
            this.txtPractica2.BorderThickness = 1;
            this.txtPractica2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPractica2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPractica2.DefaultText = "";
            this.txtPractica2.FillColor = System.Drawing.Color.White;
            this.txtPractica2.HideSelection = true;
            this.txtPractica2.IconLeft = null;
            this.txtPractica2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica2.IconPadding = 10;
            this.txtPractica2.IconRight = null;
            this.txtPractica2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica2.Lines = new string[0];
            this.txtPractica2.Location = new System.Drawing.Point(201, 343);
            this.txtPractica2.MaxLength = 32767;
            this.txtPractica2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPractica2.Modified = false;
            this.txtPractica2.Multiline = false;
            this.txtPractica2.Name = "txtPractica2";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica2.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPractica2.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica2.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica2.OnIdleState = stateProperties24;
            this.txtPractica2.Padding = new System.Windows.Forms.Padding(3);
            this.txtPractica2.PasswordChar = '\0';
            this.txtPractica2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPractica2.PlaceholderText = "Práctica 2";
            this.txtPractica2.ReadOnly = false;
            this.txtPractica2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPractica2.SelectedText = "";
            this.txtPractica2.SelectionLength = 0;
            this.txtPractica2.SelectionStart = 0;
            this.txtPractica2.ShortcutsEnabled = true;
            this.txtPractica2.Size = new System.Drawing.Size(136, 37);
            this.txtPractica2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPractica2.TabIndex = 20;
            this.txtPractica2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPractica2.TextMarginBottom = 0;
            this.txtPractica2.TextMarginLeft = 3;
            this.txtPractica2.TextMarginTop = 0;
            this.txtPractica2.TextPlaceholder = "Práctica 2";
            this.txtPractica2.UseSystemPasswordChar = false;
            this.txtPractica2.WordWrap = true;
            // 
            // txtPractica3
            // 
            this.txtPractica3.AcceptsReturn = false;
            this.txtPractica3.AcceptsTab = false;
            this.txtPractica3.AnimationSpeed = 200;
            this.txtPractica3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPractica3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPractica3.BackColor = System.Drawing.Color.White;
            this.txtPractica3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPractica3.BackgroundImage")));
            this.txtPractica3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPractica3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPractica3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPractica3.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPractica3.BorderRadius = 1;
            this.txtPractica3.BorderThickness = 1;
            this.txtPractica3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPractica3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica3.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPractica3.DefaultText = "";
            this.txtPractica3.FillColor = System.Drawing.Color.White;
            this.txtPractica3.HideSelection = true;
            this.txtPractica3.IconLeft = null;
            this.txtPractica3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica3.IconPadding = 10;
            this.txtPractica3.IconRight = null;
            this.txtPractica3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPractica3.Lines = new string[0];
            this.txtPractica3.Location = new System.Drawing.Point(372, 343);
            this.txtPractica3.MaxLength = 32767;
            this.txtPractica3.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPractica3.Modified = false;
            this.txtPractica3.Multiline = false;
            this.txtPractica3.Name = "txtPractica3";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica3.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPractica3.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica3.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPractica3.OnIdleState = stateProperties28;
            this.txtPractica3.Padding = new System.Windows.Forms.Padding(3);
            this.txtPractica3.PasswordChar = '\0';
            this.txtPractica3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPractica3.PlaceholderText = "Práctica 3";
            this.txtPractica3.ReadOnly = false;
            this.txtPractica3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPractica3.SelectedText = "";
            this.txtPractica3.SelectionLength = 0;
            this.txtPractica3.SelectionStart = 0;
            this.txtPractica3.ShortcutsEnabled = true;
            this.txtPractica3.Size = new System.Drawing.Size(136, 37);
            this.txtPractica3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPractica3.TabIndex = 21;
            this.txtPractica3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPractica3.TextMarginBottom = 0;
            this.txtPractica3.TextMarginLeft = 3;
            this.txtPractica3.TextMarginTop = 0;
            this.txtPractica3.TextPlaceholder = "Práctica 3";
            this.txtPractica3.UseSystemPasswordChar = false;
            this.txtPractica3.WordWrap = true;
            // 
            // txtPromedioPracticas
            // 
            this.txtPromedioPracticas.AcceptsReturn = false;
            this.txtPromedioPracticas.AcceptsTab = false;
            this.txtPromedioPracticas.AnimationSpeed = 200;
            this.txtPromedioPracticas.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPromedioPracticas.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPromedioPracticas.BackColor = System.Drawing.Color.White;
            this.txtPromedioPracticas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPromedioPracticas.BackgroundImage")));
            this.txtPromedioPracticas.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPromedioPracticas.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPromedioPracticas.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPromedioPracticas.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPromedioPracticas.BorderRadius = 1;
            this.txtPromedioPracticas.BorderThickness = 1;
            this.txtPromedioPracticas.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPromedioPracticas.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPromedioPracticas.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPromedioPracticas.DefaultText = "";
            this.txtPromedioPracticas.FillColor = System.Drawing.Color.White;
            this.txtPromedioPracticas.HideSelection = true;
            this.txtPromedioPracticas.IconLeft = null;
            this.txtPromedioPracticas.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPromedioPracticas.IconPadding = 10;
            this.txtPromedioPracticas.IconRight = null;
            this.txtPromedioPracticas.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPromedioPracticas.Lines = new string[0];
            this.txtPromedioPracticas.Location = new System.Drawing.Point(201, 460);
            this.txtPromedioPracticas.MaxLength = 32767;
            this.txtPromedioPracticas.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPromedioPracticas.Modified = false;
            this.txtPromedioPracticas.Multiline = false;
            this.txtPromedioPracticas.Name = "txtPromedioPracticas";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPromedioPracticas.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPromedioPracticas.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPromedioPracticas.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPromedioPracticas.OnIdleState = stateProperties32;
            this.txtPromedioPracticas.Padding = new System.Windows.Forms.Padding(3);
            this.txtPromedioPracticas.PasswordChar = '\0';
            this.txtPromedioPracticas.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPromedioPracticas.PlaceholderText = "Total";
            this.txtPromedioPracticas.ReadOnly = true;
            this.txtPromedioPracticas.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPromedioPracticas.SelectedText = "";
            this.txtPromedioPracticas.SelectionLength = 0;
            this.txtPromedioPracticas.SelectionStart = 0;
            this.txtPromedioPracticas.ShortcutsEnabled = true;
            this.txtPromedioPracticas.Size = new System.Drawing.Size(136, 37);
            this.txtPromedioPracticas.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPromedioPracticas.TabIndex = 22;
            this.txtPromedioPracticas.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPromedioPracticas.TextMarginBottom = 0;
            this.txtPromedioPracticas.TextMarginLeft = 3;
            this.txtPromedioPracticas.TextMarginTop = 0;
            this.txtPromedioPracticas.TextPlaceholder = "Total";
            this.txtPromedioPracticas.UseSystemPasswordChar = false;
            this.txtPromedioPracticas.WordWrap = true;
            // 
            // txtPromedioExamenes
            // 
            this.txtPromedioExamenes.AcceptsReturn = false;
            this.txtPromedioExamenes.AcceptsTab = false;
            this.txtPromedioExamenes.AnimationSpeed = 200;
            this.txtPromedioExamenes.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPromedioExamenes.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPromedioExamenes.BackColor = System.Drawing.Color.White;
            this.txtPromedioExamenes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPromedioExamenes.BackgroundImage")));
            this.txtPromedioExamenes.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPromedioExamenes.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPromedioExamenes.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPromedioExamenes.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPromedioExamenes.BorderRadius = 1;
            this.txtPromedioExamenes.BorderThickness = 1;
            this.txtPromedioExamenes.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPromedioExamenes.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPromedioExamenes.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPromedioExamenes.DefaultText = "";
            this.txtPromedioExamenes.FillColor = System.Drawing.Color.White;
            this.txtPromedioExamenes.HideSelection = true;
            this.txtPromedioExamenes.IconLeft = null;
            this.txtPromedioExamenes.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPromedioExamenes.IconPadding = 10;
            this.txtPromedioExamenes.IconRight = null;
            this.txtPromedioExamenes.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPromedioExamenes.Lines = new string[0];
            this.txtPromedioExamenes.Location = new System.Drawing.Point(1095, 458);
            this.txtPromedioExamenes.MaxLength = 32767;
            this.txtPromedioExamenes.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPromedioExamenes.Modified = false;
            this.txtPromedioExamenes.Multiline = false;
            this.txtPromedioExamenes.Name = "txtPromedioExamenes";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPromedioExamenes.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPromedioExamenes.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPromedioExamenes.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPromedioExamenes.OnIdleState = stateProperties36;
            this.txtPromedioExamenes.Padding = new System.Windows.Forms.Padding(3);
            this.txtPromedioExamenes.PasswordChar = '\0';
            this.txtPromedioExamenes.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPromedioExamenes.PlaceholderText = "Total";
            this.txtPromedioExamenes.ReadOnly = true;
            this.txtPromedioExamenes.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPromedioExamenes.SelectedText = "";
            this.txtPromedioExamenes.SelectionLength = 0;
            this.txtPromedioExamenes.SelectionStart = 0;
            this.txtPromedioExamenes.ShortcutsEnabled = true;
            this.txtPromedioExamenes.Size = new System.Drawing.Size(136, 37);
            this.txtPromedioExamenes.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPromedioExamenes.TabIndex = 27;
            this.txtPromedioExamenes.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPromedioExamenes.TextMarginBottom = 0;
            this.txtPromedioExamenes.TextMarginLeft = 3;
            this.txtPromedioExamenes.TextMarginTop = 0;
            this.txtPromedioExamenes.TextPlaceholder = "Total";
            this.txtPromedioExamenes.UseSystemPasswordChar = false;
            this.txtPromedioExamenes.WordWrap = true;
            // 
            // txtExamenFinal
            // 
            this.txtExamenFinal.AcceptsReturn = false;
            this.txtExamenFinal.AcceptsTab = false;
            this.txtExamenFinal.AnimationSpeed = 200;
            this.txtExamenFinal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtExamenFinal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtExamenFinal.BackColor = System.Drawing.Color.White;
            this.txtExamenFinal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtExamenFinal.BackgroundImage")));
            this.txtExamenFinal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtExamenFinal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtExamenFinal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtExamenFinal.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtExamenFinal.BorderRadius = 1;
            this.txtExamenFinal.BorderThickness = 1;
            this.txtExamenFinal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtExamenFinal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExamenFinal.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtExamenFinal.DefaultText = "";
            this.txtExamenFinal.FillColor = System.Drawing.Color.White;
            this.txtExamenFinal.HideSelection = true;
            this.txtExamenFinal.IconLeft = null;
            this.txtExamenFinal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExamenFinal.IconPadding = 10;
            this.txtExamenFinal.IconRight = null;
            this.txtExamenFinal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExamenFinal.Lines = new string[0];
            this.txtExamenFinal.Location = new System.Drawing.Point(1266, 343);
            this.txtExamenFinal.MaxLength = 32767;
            this.txtExamenFinal.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtExamenFinal.Modified = false;
            this.txtExamenFinal.Multiline = false;
            this.txtExamenFinal.Name = "txtExamenFinal";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExamenFinal.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtExamenFinal.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExamenFinal.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExamenFinal.OnIdleState = stateProperties40;
            this.txtExamenFinal.Padding = new System.Windows.Forms.Padding(3);
            this.txtExamenFinal.PasswordChar = '\0';
            this.txtExamenFinal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtExamenFinal.PlaceholderText = "Examen Final";
            this.txtExamenFinal.ReadOnly = false;
            this.txtExamenFinal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtExamenFinal.SelectedText = "";
            this.txtExamenFinal.SelectionLength = 0;
            this.txtExamenFinal.SelectionStart = 0;
            this.txtExamenFinal.ShortcutsEnabled = true;
            this.txtExamenFinal.Size = new System.Drawing.Size(136, 37);
            this.txtExamenFinal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtExamenFinal.TabIndex = 26;
            this.txtExamenFinal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtExamenFinal.TextMarginBottom = 0;
            this.txtExamenFinal.TextMarginLeft = 3;
            this.txtExamenFinal.TextMarginTop = 0;
            this.txtExamenFinal.TextPlaceholder = "Examen Final";
            this.txtExamenFinal.UseSystemPasswordChar = false;
            this.txtExamenFinal.WordWrap = true;
            // 
            // txtParcial2
            // 
            this.txtParcial2.AcceptsReturn = false;
            this.txtParcial2.AcceptsTab = false;
            this.txtParcial2.AnimationSpeed = 200;
            this.txtParcial2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParcial2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParcial2.BackColor = System.Drawing.Color.White;
            this.txtParcial2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParcial2.BackgroundImage")));
            this.txtParcial2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParcial2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtParcial2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParcial2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParcial2.BorderRadius = 1;
            this.txtParcial2.BorderThickness = 1;
            this.txtParcial2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParcial2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParcial2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtParcial2.DefaultText = "";
            this.txtParcial2.FillColor = System.Drawing.Color.White;
            this.txtParcial2.HideSelection = true;
            this.txtParcial2.IconLeft = null;
            this.txtParcial2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParcial2.IconPadding = 10;
            this.txtParcial2.IconRight = null;
            this.txtParcial2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParcial2.Lines = new string[0];
            this.txtParcial2.Location = new System.Drawing.Point(1095, 343);
            this.txtParcial2.MaxLength = 32767;
            this.txtParcial2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtParcial2.Modified = false;
            this.txtParcial2.Multiline = false;
            this.txtParcial2.Name = "txtParcial2";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParcial2.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtParcial2.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParcial2.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParcial2.OnIdleState = stateProperties44;
            this.txtParcial2.Padding = new System.Windows.Forms.Padding(3);
            this.txtParcial2.PasswordChar = '\0';
            this.txtParcial2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParcial2.PlaceholderText = "Parcial 2";
            this.txtParcial2.ReadOnly = false;
            this.txtParcial2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParcial2.SelectedText = "";
            this.txtParcial2.SelectionLength = 0;
            this.txtParcial2.SelectionStart = 0;
            this.txtParcial2.ShortcutsEnabled = true;
            this.txtParcial2.Size = new System.Drawing.Size(136, 37);
            this.txtParcial2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtParcial2.TabIndex = 25;
            this.txtParcial2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParcial2.TextMarginBottom = 0;
            this.txtParcial2.TextMarginLeft = 3;
            this.txtParcial2.TextMarginTop = 0;
            this.txtParcial2.TextPlaceholder = "Parcial 2";
            this.txtParcial2.UseSystemPasswordChar = false;
            this.txtParcial2.WordWrap = true;
            // 
            // GraficaPromedioExamen
            // 
            this.GraficaPromedioExamen.Animated = false;
            this.GraficaPromedioExamen.AnimationInterval = 1;
            this.GraficaPromedioExamen.AnimationSpeed = 1;
            this.GraficaPromedioExamen.BackColor = System.Drawing.Color.Transparent;
            this.GraficaPromedioExamen.CircleMargin = 10;
            this.GraficaPromedioExamen.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GraficaPromedioExamen.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.GraficaPromedioExamen.IsPercentage = false;
            this.GraficaPromedioExamen.LineProgressThickness = 10;
            this.GraficaPromedioExamen.LineThickness = 10;
            this.GraficaPromedioExamen.Location = new System.Drawing.Point(1114, 524);
            this.GraficaPromedioExamen.Name = "GraficaPromedioExamen";
            this.GraficaPromedioExamen.ProgressAnimationSpeed = 200;
            this.GraficaPromedioExamen.ProgressBackColor = System.Drawing.Color.Gainsboro;
            this.GraficaPromedioExamen.ProgressColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(177)))), ((int)(((byte)(137)))));
            this.GraficaPromedioExamen.ProgressColor2 = System.Drawing.Color.DodgerBlue;
            this.GraficaPromedioExamen.ProgressEndCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.GraficaPromedioExamen.ProgressFillStyle = Bunifu.UI.WinForms.BunifuCircleProgress.FillStyles.Solid;
            this.GraficaPromedioExamen.ProgressStartCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.GraficaPromedioExamen.SecondaryFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.GraficaPromedioExamen.Size = new System.Drawing.Size(100, 100);
            this.GraficaPromedioExamen.SubScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.GraficaPromedioExamen.SubScriptMargin = new System.Windows.Forms.Padding(5, -20, 0, 0);
            this.GraficaPromedioExamen.SubScriptText = "";
            this.GraficaPromedioExamen.SuperScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.GraficaPromedioExamen.SuperScriptMargin = new System.Windows.Forms.Padding(5, 20, 0, 0);
            this.GraficaPromedioExamen.SuperScriptText = "%";
            this.GraficaPromedioExamen.TabIndex = 24;
            this.GraficaPromedioExamen.Text = "30";
            this.GraficaPromedioExamen.TextMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.GraficaPromedioExamen.Value = 30;
            this.GraficaPromedioExamen.ValueByTransition = 30;
            this.GraficaPromedioExamen.ValueMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            // 
            // txtParcial1
            // 
            this.txtParcial1.AcceptsReturn = false;
            this.txtParcial1.AcceptsTab = false;
            this.txtParcial1.AnimationSpeed = 200;
            this.txtParcial1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParcial1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParcial1.BackColor = System.Drawing.Color.White;
            this.txtParcial1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParcial1.BackgroundImage")));
            this.txtParcial1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParcial1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtParcial1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParcial1.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParcial1.BorderRadius = 1;
            this.txtParcial1.BorderThickness = 1;
            this.txtParcial1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParcial1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParcial1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtParcial1.DefaultText = "";
            this.txtParcial1.FillColor = System.Drawing.Color.White;
            this.txtParcial1.HideSelection = true;
            this.txtParcial1.IconLeft = null;
            this.txtParcial1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParcial1.IconPadding = 10;
            this.txtParcial1.IconRight = null;
            this.txtParcial1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParcial1.Lines = new string[0];
            this.txtParcial1.Location = new System.Drawing.Point(915, 343);
            this.txtParcial1.MaxLength = 32767;
            this.txtParcial1.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtParcial1.Modified = false;
            this.txtParcial1.Multiline = false;
            this.txtParcial1.Name = "txtParcial1";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParcial1.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtParcial1.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParcial1.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParcial1.OnIdleState = stateProperties48;
            this.txtParcial1.Padding = new System.Windows.Forms.Padding(3);
            this.txtParcial1.PasswordChar = '\0';
            this.txtParcial1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParcial1.PlaceholderText = "Parcial 1";
            this.txtParcial1.ReadOnly = false;
            this.txtParcial1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParcial1.SelectedText = "";
            this.txtParcial1.SelectionLength = 0;
            this.txtParcial1.SelectionStart = 0;
            this.txtParcial1.ShortcutsEnabled = true;
            this.txtParcial1.Size = new System.Drawing.Size(136, 37);
            this.txtParcial1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtParcial1.TabIndex = 23;
            this.txtParcial1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParcial1.TextMarginBottom = 0;
            this.txtParcial1.TextMarginLeft = 3;
            this.txtParcial1.TextMarginTop = 0;
            this.txtParcial1.TextPlaceholder = "Parcial 1";
            this.txtParcial1.UseSystemPasswordChar = false;
            this.txtParcial1.WordWrap = true;
            // 
            // lblPractica
            // 
            this.lblPractica.AutoSize = true;
            this.lblPractica.Font = new System.Drawing.Font("Century Gothic", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPractica.ForeColor = System.Drawing.Color.Black;
            this.lblPractica.Location = new System.Drawing.Point(201, 266);
            this.lblPractica.Name = "lblPractica";
            this.lblPractica.Size = new System.Drawing.Size(134, 32);
            this.lblPractica.TabIndex = 28;
            this.lblPractica.Text = "Practicas";
            // 
            // lblExamenes
            // 
            this.lblExamenes.AutoSize = true;
            this.lblExamenes.Font = new System.Drawing.Font("Century Gothic", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblExamenes.ForeColor = System.Drawing.Color.Black;
            this.lblExamenes.Location = new System.Drawing.Point(1090, 266);
            this.lblExamenes.Name = "lblExamenes";
            this.lblExamenes.Size = new System.Drawing.Size(148, 32);
            this.lblExamenes.TabIndex = 29;
            this.lblExamenes.Text = "Examenes";
            // 
            // lblPromedioPracticas
            // 
            this.lblPromedioPracticas.AutoSize = true;
            this.lblPromedioPracticas.Font = new System.Drawing.Font("Century Gothic", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPromedioPracticas.ForeColor = System.Drawing.Color.Black;
            this.lblPromedioPracticas.Location = new System.Drawing.Point(231, 413);
            this.lblPromedioPracticas.Name = "lblPromedioPracticas";
            this.lblPromedioPracticas.Size = new System.Drawing.Size(74, 32);
            this.lblPromedioPracticas.TabIndex = 30;
            this.lblPromedioPracticas.Text = "Total";
            // 
            // lblPromedioExamenes
            // 
            this.lblPromedioExamenes.AutoSize = true;
            this.lblPromedioExamenes.Font = new System.Drawing.Font("Century Gothic", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPromedioExamenes.ForeColor = System.Drawing.Color.Black;
            this.lblPromedioExamenes.Location = new System.Drawing.Point(1127, 413);
            this.lblPromedioExamenes.Name = "lblPromedioExamenes";
            this.lblPromedioExamenes.Size = new System.Drawing.Size(74, 32);
            this.lblPromedioExamenes.TabIndex = 31;
            this.lblPromedioExamenes.Text = "Total";
            this.lblPromedioExamenes.Click += new System.EventHandler(this.lblPromedioExamenes_Click);
            // 
            // btnAgregar
            // 
            this.btnAgregar.BackColor = System.Drawing.Color.BurlyWood;
            this.btnAgregar.FlatAppearance.BorderSize = 0;
            this.btnAgregar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgregar.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.btnAgregar.Location = new System.Drawing.Point(578, 326);
            this.btnAgregar.Name = "btnAgregar";
            this.btnAgregar.Size = new System.Drawing.Size(305, 74);
            this.btnAgregar.TabIndex = 32;
            this.btnAgregar.Text = "Registrar Califcación Estudiante";
            this.btnAgregar.UseVisualStyleBackColor = false;
            this.btnAgregar.UseWaitCursor = true;
            this.btnAgregar.Click += new System.EventHandler(this.btnAgregar_Click);
            // 
            // Registrar_calificacion
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Wheat;
            this.Controls.Add(this.btnAgregar);
            this.Controls.Add(this.lblPromedioExamenes);
            this.Controls.Add(this.lblPromedioPracticas);
            this.Controls.Add(this.lblExamenes);
            this.Controls.Add(this.lblPractica);
            this.Controls.Add(this.txtPromedioExamenes);
            this.Controls.Add(this.txtExamenFinal);
            this.Controls.Add(this.txtParcial2);
            this.Controls.Add(this.GraficaPromedioExamen);
            this.Controls.Add(this.txtParcial1);
            this.Controls.Add(this.txtPromedioPracticas);
            this.Controls.Add(this.txtPractica3);
            this.Controls.Add(this.txtPractica2);
            this.Controls.Add(this.pnlIdentificacion);
            this.Controls.Add(this.GraficaPromedioPractica);
            this.Controls.Add(this.txtPractica1);
            this.Name = "Registrar_calificacion";
            this.Size = new System.Drawing.Size(1419, 662);
            this.pnlIdentificacion.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtPractica1;
        private Bunifu.UI.WinForms.BunifuCircleProgress GraficaPromedioPractica;
        private System.Windows.Forms.Panel pnlIdentificacion;
        private Bunifu.UI.WinForms.BunifuTextBox txtPractica2;
        private Bunifu.UI.WinForms.BunifuTextBox txtPractica3;
        private Bunifu.UI.WinForms.BunifuTextBox txtPromedioPracticas;
        private Bunifu.UI.WinForms.BunifuTextBox txtPromedioExamenes;
        private Bunifu.UI.WinForms.BunifuTextBox txtExamenFinal;
        private Bunifu.UI.WinForms.BunifuTextBox txtParcial2;
        private Bunifu.UI.WinForms.BunifuCircleProgress GraficaPromedioExamen;
        private Bunifu.UI.WinForms.BunifuTextBox txtParcial1;
        private System.Windows.Forms.Label lblPractica;
        private System.Windows.Forms.Label lblExamenes;
        private System.Windows.Forms.Label lblPromedioPracticas;
        private System.Windows.Forms.Label lblPromedioExamenes;
        private System.Windows.Forms.Button btnAgregar;
        private Bunifu.UI.WinForms.BunifuTextBox txtStatus;
        private Bunifu.UI.WinForms.BunifuTextBox txtMatricula;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtCalificacionFinal;
    }
}
